/**
 * The In plain words fixtures — real `answer-account` replies generated by
 * `fixtures/generate.ts` from the archived field run (never hand-authored).
 * A test that needs a shape the run did not produce edits a deep copy in the
 * test, in plain sight (the `loadTampered` precedent of test/served/helpers.ts).
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AnswerAccount, AnswerAccountShownLeaf } from 'agentfootprint/observe';

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), 'fixtures');

export interface AccountReply {
  readonly account: AnswerAccount;
  readonly shown: Record<string, AnswerAccountShownLeaf>;
}

/** Mutable deep copy, for a test's own edit. */
type Mutable<T> = { -readonly [K in keyof T]: Mutable<T[K]> };

/** `A` = with the app's declarations (what the field app's server returns); `A0` = the library alone. */
export function loadReply(which: 'A' | 'A0' = 'A'): AccountReply {
  const file = which === 'A' ? 'answer-account-turn2.json' : 'answer-account-turn2-bare.json';
  return JSON.parse(readFileSync(join(FIXTURES, file), 'utf8')) as AccountReply;
}

/** A deep copy of a reply, edited by `edit` — the one way a test shapes an account the run did not. */
export function tamperedReply(edit: (reply: Mutable<AccountReply>) => void, which: 'A' | 'A0' = 'A'): AccountReply {
  const reply = structuredClone(loadReply(which)) as Mutable<AccountReply>;
  edit(reply);
  return reply as AccountReply;
}

export type { Mutable };
