/** @vitest-environment jsdom */
/**
 * The Time band brought up to agentfootprint 9.132.0, over REAL rows
 * (test/time/fixtures/time-rows-9.132.json, generated by `npm run
 * fixtures:time` from scripted runs — no model called):
 *
 *   L1  the three new row kinds are folded — `time-answer` (joined to its
 *       reading by mention), `time-derived` (per turn), `source-clock` (per
 *       call, with its zone) — and the `period` row's result checks are
 *       carried and drawn (`differs`, `shifted`, `beyondRetention`,
 *       `partlyBeyondRetention`), each only where the row carries it;
 *   L2  a reading left `open` that the person answered reads as SETTLED by
 *       the person (`confirmed` / `edited`), with the answered window — read
 *       only off the `time-answer` row;
 *   L3  `<TimeView>` mounts the standing, the time ask and the band in one
 *       tab-ready view, from both barrels;
 *   L4  the answer's time standing lists ONLY the time reasons the library's
 *       assessment names — never one computed from the rows.
 */
import React from 'react';
import '@testing-library/jest-dom/vitest';
import { afterEach, describe, expect, it } from 'vitest';
import { cleanup, render, screen, within } from '@testing-library/react';

import { answerOfReading, foldTimeRows, spellMs } from '../../src/core/time/timeRows.js';
import { timeStandingOf } from '../../src/core/time/timeStanding.js';
import { LABELS } from '../../src/core/time/labels.js';
import { TimeBand } from '../../src/react/components/TimeBand.js';
import { TimeView } from '../../src/react/components/TimeView.js';
import * as root from '../../src/index.js';
import * as contextDoor from '../../src/context/index.js';
import fixtures from './fixtures/time-rows-9.132.json';
import older from './fixtures/time-rows.json';

afterEach(cleanup);

type Row = Record<string, unknown> & { kind: string };
type Range = { from: string; to: string };
type Scenario = { readonly ledger: readonly Row[]; readonly coverage: readonly unknown[]; readonly assessment?: unknown };
const S = fixtures as unknown as Record<string, Scenario>;
const OLD = older as unknown as Record<string, Scenario>;
const rowsOf = (s: Scenario, kind: string) => s.ledger.filter((r) => r.kind === kind);
/** One row of `kind`, typed as the test reads it (the fixture is JSON). */
const rowOf = <T = Row,>(s: Scenario, kind: string, i = 0): T => rowsOf(s, kind)[i] as unknown as T;
const span = (r: Range) => `[${r.from}, ${r.to})`;
const callEl = (id: string) =>
  screen.getAllByTestId('time-call').find((el) => el.getAttribute('data-tool-call-id') === id)!;
const periodOf = (s: Scenario, id: string) =>
  rowsOf(s, 'period').find((r) => r.toolCallId === id) as Row & {
    differs?: { against: string; source: string; asked: Range; read: Range[]; missing: Range[]; extra: Range[]; stepMs?: number };
    shifted?: { byMs: number };
  };

// ─── L1 · the fold ────────────────────────────────────────────────────────

describe('L1 — the three new row kinds and the period checks are folded', () => {
  it('the generated record carries every new kind (the fixture is the library’s, not hand-written)', () => {
    expect(rowsOf(S.confirmed!, 'time-answer')).toHaveLength(1);
    expect(rowsOf(S.confirmed!, 'time-derived')).toHaveLength(1);
    expect(rowsOf(S.checks!, 'source-clock')).toHaveLength(1);
    expect(periodOf(S.checks!, 'c1').differs).toBeDefined();
    expect(periodOf(S.checks!, 'c2').beyondRetention).toBe(true);
    expect(periodOf(S.shifted!, 'c1').shifted).toEqual({ byMs: 30 * 60_000 });
  });

  it('time-answer and time-derived land under their turn; every time row is counted', () => {
    const s = S.confirmed!;
    const fold = foldTimeRows(s.ledger, s.coverage)!;
    const [turn] = fold.turns;
    expect(turn!.answers).toEqual(rowsOf(s, 'time-answer'));
    expect(turn!.derived).toEqual(rowsOf(s, 'time-derived'));
    const kinds = new Set(['clock', 'time-reading', 'call-window', 'call', 'period', 'time-answer', 'time-derived']);
    expect(fold.rows).toBe(s.ledger.filter((r) => kinds.has(r.kind)).length);
  });

  it('source-clock joins its call by toolCallId, with its zone', () => {
    const s = S.checks!;
    const sc = rowOf<{ toolCallId: string; zone: string }>(s, 'source-clock');
    const call = foldTimeRows(s.ledger, s.coverage)!.turns[0]!.calls.find((c) => c.toolCallId === sc.toolCallId)!;
    expect(call.sourceClocks).toEqual([sc]);
  });

  it('the period row keeps its result checks as the record holds them', () => {
    const s = S.checks!;
    const calls = foldTimeRows(s.ledger, s.coverage)!.turns[0]!.calls;
    for (const id of ['c1', 'c2', 'c3']) {
      expect(calls.find((c) => c.toolCallId === id)!.period).toEqual(periodOf(s, id));
    }
    const shifted = foldTimeRows(S.shifted!.ledger)!.turns[0]!.calls[0]!.period!;
    expect(shifted.shifted).toEqual({ byMs: 30 * 60_000 });
  });

  it('a malformed check is passed over; the verdict still reads', () => {
    const s = S.checks!;
    const broken = s.ledger.map((r) =>
      r.kind === 'period' && r.toolCallId === 'c1' ? { ...r, differs: { against: 'asked' }, shifted: 'soon' } : r,
    );
    const p = foldTimeRows(broken)!.turns[0]!.calls.find((c) => c.toolCallId === 'c1')!.period!;
    expect(p.verdict).toBe(periodOf(s, 'c1').verdict);
    expect(p).not.toHaveProperty('differs');
    expect(p).not.toHaveProperty('shifted');
  });

  it('a ledger holding only new-kind rows still makes a band (omit, never deny — in both directions)', () => {
    const only = [rowOf(S.confirmed!, 'time-derived')];
    expect(foldTimeRows(only)?.rows).toBe(1);
  });
});

// ─── L1 · drawn ───────────────────────────────────────────────────────────

describe('L1 — the band draws the checks, the source clock and the derived values', () => {
  it('differs: against, the range compared, what was read, the source, the step, and missing', () => {
    const s = S.checks!;
    const p = periodOf(s, 'c1');
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    const d = within(callEl('c1')).getByTestId('time-differs');
    expect(d).toHaveAttribute('data-against', p.differs!.against);
    expect(d).toHaveAttribute('data-source', p.differs!.source);
    expect(within(d).getByTestId('time-differs-flag')).toHaveTextContent(LABELS.differs);
    expect(d).toHaveTextContent(span(p.differs!.asked));
    for (const r of p.differs!.read) expect(d).toHaveTextContent(span(r));
    for (const r of p.differs!.missing) expect(within(d).getByTestId('time-differs-missing')).toHaveTextContent(span(r));
    expect(d).toHaveTextContent(`${LABELS.step} ${p.differs!.stepMs}`);
    expect(within(d).queryByTestId('time-differs-extra')).toBeNull(); // the row's `extra` is empty
  });

  it('a window the model chose is judged against the person’s — the record’s word, printed', () => {
    const s = S.checks!;
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    expect(within(callEl('c3')).getByTestId('time-differs')).toHaveAttribute('data-against', 'person');
  });

  it('beyond retention and partly beyond retention, each only on the row that carries it', () => {
    const s = S.checks!;
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    expect(within(callEl('c2')).getByTestId('time-beyond-retention')).toHaveTextContent(LABELS.beyondRetention);
    expect(within(callEl('c3')).getByTestId('time-period-partly-beyond-retention')).toBeInTheDocument();
    expect(within(callEl('c1')).queryByTestId('time-beyond-retention')).toBeNull();
    expect(within(callEl('c1')).queryByTestId('time-period-partly-beyond-retention')).toBeNull();
  });

  it('shifted: the record’s byMs, spelled exactly, beside missing AND extra', () => {
    const s = S.shifted!;
    const p = periodOf(s, 'c1');
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    const el = callEl('c1');
    const shifted = within(el).getByTestId('time-shifted');
    expect(shifted).toHaveAttribute('data-by-ms', String(p.shifted!.byMs));
    expect(shifted).toHaveTextContent(spellMs(p.shifted!.byMs));
    for (const r of p.differs!.extra) expect(within(el).getByTestId('time-differs-extra')).toHaveTextContent(span(r));
    for (const r of p.differs!.missing) expect(within(el).getByTestId('time-differs-missing')).toHaveTextContent(span(r));
  });

  it('the source clock’s zone on its call', () => {
    const s = S.checks!;
    const sc = rowOf<{ toolCallId: string; zone: string }>(s, 'source-clock');
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    expect(within(callEl(sc.toolCallId)).getByTestId('time-source-clock')).toHaveTextContent(sc.zone);
  });

  it('the values the library derived from a reading', () => {
    const s = S.confirmed!;
    const d = rowOf<{ values: string[] }>(s, 'time-derived');
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    const el = screen.getByTestId('time-derived');
    expect(el).toHaveTextContent(LABELS.derived);
    for (const v of d.values) expect(el).toHaveTextContent(v);
  });

  it('never infer: a 9.129.0 record (no checks on its period rows) draws no check', () => {
    const s = OLD.controlWindow!;
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    for (const id of ['time-differs', 'time-shifted', 'time-beyond-retention', 'time-source-clock', 'time-derived']) {
      expect(screen.queryByTestId(id)).toBeNull();
    }
  });
});

// ─── L2 · the reading the person settled ─────────────────────────────────

describe('L2 — an open reading the person answered reads as settled by the person', () => {
  it('confirmed: the record’s `open` choice stays, and the answered window is shown beside it', () => {
    const s = S.confirmed!;
    const reading = rowOf<{ choice: { by: string } }>(s, 'time-reading');
    const answer = rowOf<Range & { how: string; zone: string; mention: number }>(s, 'time-answer');
    expect(reading.choice.by).toBe('open'); // 9.132.0: every reading is a proposal
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    const el = screen.getByTestId('time-reading');
    expect(el).toHaveAttribute('data-choice', 'open');
    expect(el).toHaveAttribute('data-settled', 'confirmed');
    const settled = within(el).getByTestId('time-reading-answer');
    expect(settled).toHaveAttribute('data-how', answer.how);
    expect(el).toHaveTextContent(LABELS.answered);
    expect(settled).toHaveTextContent(span(answer));
    expect(settled).toHaveTextContent(answer.zone);
  });

  it('edited: the person wrote their own window — the record’s word is printed', () => {
    const s = S.confirmed!;
    const ledger = s.ledger.map((r) =>
      r.kind === 'time-answer' ? { ...r, how: 'edited', from: '2026-10-09T08:00:00-07:00', to: '2026-10-09T09:00:00-07:00' } : r,
    );
    render(<TimeBand rows={ledger} />);
    const el = screen.getByTestId('time-reading');
    expect(el).toHaveAttribute('data-settled', 'edited');
    expect(within(el).getByTestId('time-reading-answer')).toHaveTextContent('[2026-10-09T08:00:00-07:00, 2026-10-09T09:00:00-07:00)');
  });

  it('an open reading nobody answered stays open — no settled line', () => {
    const s = OLD.openReading!;
    render(<TimeBand rows={s.ledger} coverage={s.coverage} />);
    const el = screen.getByTestId('time-reading');
    expect(el).toHaveAttribute('data-choice', 'open');
    expect(el).toHaveAttribute('data-settled', '');
    expect(within(el).queryByTestId('time-reading-answer')).toBeNull();
  });

  it('joined by mention within the turn; the LATEST answer for the mention binds', () => {
    const s = S.confirmed!;
    const answer = rowOf(s, 'time-answer');
    const later = { ...answer, how: 'edited', to: '2026-10-09T08:30:00-07:00' };
    const otherTurn = { ...answer, turn: 2, how: 'edited' };
    const fold = foldTimeRows([...s.ledger, later, otherTurn])!;
    const turn1 = fold.turns.find((t) => t.turn === 1)!;
    expect(answerOfReading(turn1, rowOf<{ mention?: number }>(s, 'time-reading'))).toEqual(later);
    expect(answerOfReading(turn1, { mention: 1 })).toBeUndefined();
    expect(answerOfReading(turn1, {})).toBeUndefined();
  });

  it('an answer whose mention no reading carries is still drawn, on its own line', () => {
    const s = S.confirmed!;
    const ledger = s.ledger.map((r) => (r.kind === 'time-answer' ? { ...r, mention: 3 } : r));
    render(<TimeBand rows={ledger} />);
    expect(screen.getByTestId('time-reading')).toHaveAttribute('data-settled', '');
    expect(screen.getByTestId('time-answer')).toHaveAttribute('data-how', 'confirmed');
  });
});

// ─── L4 · the answer's time standing ─────────────────────────────────────

describe('L4 — the time reasons the library filed, and only those', () => {
  const reasonNames = (s: Scenario) =>
    ((s.assessment as { reasons: { reason: string }[] }).reasons ?? []).map((r) => r.reason);

  it('confirmed: period-undeclared and derived-from-reading, in the library’s order', () => {
    const s = S.confirmed!;
    expect(reasonNames(s)).toEqual(['period-undeclared', 'derived-from-reading']);
    const t = timeStandingOf(s.assessment, s.ledger)!;
    expect(t.standing).toBe('not-sure');
    expect(t.reasons.map((r) => r.reason)).toEqual(['period-undeclared', 'derived-from-reading']);
    expect(t.reasons[0]!.calls).toEqual([{ toolCallId: 'c1', toolName: 'client_activity' }]);
    expect(t.reasons[1]!.calls).toEqual([]); // an answer-level reason names no call
  });

  it('checks: a non-time reason is not listed; each time reason names the calls its witnesses point at', () => {
    const s = S.checks!;
    expect(reasonNames(s)).toContain('argument-unverified');
    const t = timeStandingOf(s.assessment, s.ledger)!;
    expect(t.reasons.map((r) => r.reason)).toEqual([
      'period-undeclared',
      'period-differs-from-asked',
      'period-beyond-retention',
    ]);
    const callsOf = (reason: string) => t.reasons.find((r) => r.reason === reason)!.calls.map((c) => c.toolCallId);
    expect(callsOf('period-differs-from-asked')).toEqual(['c1', 'c3']);
    expect(callsOf('period-beyond-retention')).toEqual(['c2']);
  });

  it('argument-assumed is listed when its witness is a PERIOD argument', () => {
    const s = S.shifted!;
    const t = timeStandingOf(s.assessment, s.ledger)!;
    expect(t.reasons.map((r) => r.reason)).toEqual([
      'argument-assumed',
      'period-undeclared',
      'period-differs-from-asked',
    ]);
    expect(t.reasons[0]!.calls).toEqual([{ toolCallId: 'c1', toolName: 'client_activity' }]);
  });

  it('argument-assumed on a non-period argument, or with no witness to read, is passed over', () => {
    const s = S.shifted!;
    const ledger = s.ledger.map((r) => (r.kind === 'argument' ? { ...r, period: undefined } : r));
    expect(timeStandingOf(s.assessment, ledger)!.reasons.map((r) => r.reason)).not.toContain('argument-assumed');
    // The data projection (`turn_end.answerAssessment`): reason names only.
    const data = { assessment: 'unknown', standing: 'not-sure', reasons: ['argument-assumed', 'period-unknown'], checked: [] };
    const t = timeStandingOf({ answerAssessment: data }, s.ledger)!;
    expect(t.reasons).toEqual([{ reason: 'period-unknown', calls: [] }]);
  });

  it('never computes a reason: rows that carry a check, with no assessment, list nothing', () => {
    const s = S.checks!;
    expect(timeStandingOf(undefined, s.ledger)).toBeUndefined();
    expect(timeStandingOf({ standing: 'consistent', reasons: [] }, s.ledger)).toBeUndefined();
    expect(timeStandingOf({ standing: 'not-sure', reasons: [{ reason: 'value-unsupported', witness: [] }] }, s.ledger)).toBeUndefined();
  });

  it('a witness pointer that names no row (another key, a bad path, an index past the end) names no call', () => {
    const t = timeStandingOf(
      {
        reasons: [
          {
            reason: 'period-not-held',
            witness: [
              { kind: 'state', key: 'coverageDeclared', path: '/0/period' },
              { kind: 'state', key: 'findingsLedger', path: 'nope' },
              { kind: 'state', key: 'findingsLedger', path: '/999/verdict' },
              { kind: 'history', index: 0, path: '/toolCallId' },
            ],
          },
        ],
      },
      S.checks!.ledger,
    )!;
    expect(t.reasons).toEqual([{ reason: 'period-not-held', calls: [] }]);
    expect(t).not.toHaveProperty('standing');
  });

  it('every time reason has a plain label', () => {
    for (const r of ['period-differs-from-asked', 'period-beyond-retention', 'period-not-held', 'period-partly-held', 'period-unknown', 'period-undeclared', 'derived-from-reading', 'argument-assumed'] as const) {
      expect(LABELS[r]).toMatch(/\S/);
    }
  });
});

// ─── L3 · the mountable view ──────────────────────────────────────────────

describe('L3 — <TimeView>: standing, ask and band in one tab-ready view', () => {
  it('is exported from the root barrel and the context door', () => {
    expect(root.TimeView).toBe(TimeView);
    expect(contextDoor.TimeView).toBe(TimeView);
    expect(typeof root.timeStandingOf).toBe('function');
    expect(typeof root.answerOfReading).toBe('function');
  });

  it('draws the time reasons with their labels, the ask, and the band', () => {
    const s = S.checks!;
    const ask = (S.ask as unknown as { first: unknown }).first;
    render(<TimeView rows={s.ledger} coverage={s.coverage} assessment={s.assessment} ask={ask} />);
    const view = screen.getByTestId('time-view');
    const standing = within(view).getByTestId('time-standing');
    expect(standing).toHaveAttribute('data-standing', 'not-sure');
    const items = within(standing).getAllByTestId('time-reason');
    expect(items.map((el) => el.getAttribute('data-reason'))).toEqual([
      'period-undeclared',
      'period-differs-from-asked',
      'period-beyond-retention',
    ]);
    expect(items[1]).toHaveTextContent(LABELS['period-differs-from-asked']);
    expect(items[1]).toHaveTextContent('c1');
    expect(items[1]).toHaveTextContent('c3');
    expect(within(standing).queryByText(/argument-unverified/)).toBeNull();
    expect(within(view).getByTestId('time-ask')).toBeInTheDocument();
    expect(within(view).getByTestId('time-band')).toBeInTheDocument();
  });

  it('omits the standing section when no time reason holds', () => {
    const s = S.checks!;
    render(<TimeView rows={s.ledger} assessment={{ standing: 'consistent', reasons: [] }} />);
    expect(screen.queryByTestId('time-standing')).toBeNull();
    expect(screen.getByTestId('time-band')).toBeInTheDocument();
  });

  it('renders nothing with no time row, no time ask and no time reason', () => {
    const { container } = render(
      <TimeView rows={[{ kind: 'standing', toolCallId: 'c1', standing: 'fact' }]} ask={{ fields: [{ id: 'x', type: 'string' }] }} />,
    );
    expect(container).toBeEmptyDOMElement();
    cleanup();
    expect(render(<TimeView />).container).toBeEmptyDOMElement();
  });

  it('draws exactly the band <TimeBand> draws for the same rows', () => {
    const s = S.confirmed!;
    const band = render(<TimeBand rows={s.ledger} coverage={s.coverage} />).container.innerHTML;
    cleanup();
    render(<TimeView rows={s.ledger} coverage={s.coverage} />);
    expect(screen.getByTestId('time-band').outerHTML).toBe(band);
  });
});
