/**
 * The 9.50.0 era split, over TWO REAL ARTIFACTS — no synthetic events here.
 *
 * agentfootprint 9.50.0 put three routing facts on the recording as data:
 * the author's declared map (`skill.graph_declared`), the reachable set on
 * every cursor move (`cursorMove.reachable`), and the opt-in assembled system
 * prompt (`llm_start.systemPromptText`). The selectors consume all three —
 * and must keep telling the truth for every recording made BEFORE them.
 *
 * So this file replays the same demo agent from both eras:
 *
 *   NEW  `demo/skill-run.json` — the checked-in demo fixture, regenerated by
 *        `demo/generate-skill-run.ts` on agentfootprint ^9.50.0 with
 *        `recordSystemPrompt: true`. Reading it from here doubles as a guard:
 *        regenerate it with an older library (or without the opt-in) and this
 *        file fails instead of the demo quietly losing its facts.
 *   OLD  `__fixtures__/skill-run-pre-950.json` — the SAME demo agent's run,
 *        frozen exactly as the 9.49-era generator wrote it (a byte copy, never
 *        hand-edited). It is what every recording archived before 9.50.0
 *        looks like, and the fallback paths run against it for real.
 *
 * What must differ between the eras is exactly the three facts — and what
 * must NOT differ is everything the old fold already promised.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';

import { observeRecording, type Recording } from '../observeRecording.js';
import { selectSkillRoute, type SkillRoute } from './selectSkillRoute.js';
import { selectSkillBeats } from './selectSkillBeats.js';
import { selectSkillTopology } from './selectSkillTopology.js';

const HERE = dirname(fileURLToPath(import.meta.url));

function routeFrom(file: string): SkillRoute {
  const recording = JSON.parse(readFileSync(file, 'utf8')) as Recording;
  return selectSkillRoute({ log: observeRecording(recording).recorder.selectEventLog() });
}

const NEW_ERA = join(HERE, '..', '..', '..', 'demo', 'skill-run.json');
const OLD_ERA = join(HERE, '..', '__fixtures__', 'skill-run-pre-950.json');

describe('a 9.50.0 recording — the recording carries the map', () => {
  const route = routeFrom(NEW_ERA);

  it('takes the declared set from skill.graph_declared, and says it is COMPLETE', () => {
    expect(route.declaredComplete).toBe(true);
    // The author drew six routes; the run fired only two of them. The map on
    // the record is the whole declaration, not the fired lower bound.
    expect(route.declaredEdges).toHaveLength(6);
    const byId = new Map(route.declaredEdges.map((e) => [`${e.from}->${e.to}`, e]));
    // An edge the run never took is still on the map — the completeness fact.
    expect(byId.get('disputes->security')).toBeDefined();
    expect(byId.get('billing->refunds')!.triggerKind).toBe('on-tool-return');
    expect(byId.get('support->billing')!.triggerKind).toBe('model');
  });

  it('keeps the synthetic START apart as the entry fact, never as an edge', () => {
    expect(route.entryIds).toEqual(['support']);
    expect(route.declaredEdges.some((e) => e.from === 'support' && e.to === 'support')).toBe(false);
  });

  it('node descriptions come free with the declared map', () => {
    const support = route.nodes.find((n) => n.id === 'support');
    expect(support?.description).toBe('Classify and route the customer request.');
    expect(support?.kind).toBe('skill');
  });

  it('fills every beat\'s reachable set from cursorMove.reachable — the exact source', () => {
    const beats = selectSkillBeats({ route });
    expect(beats.length).toBeGreaterThan(0);
    for (const beat of beats) {
      expect(beat.reachable?.source).toBe('cursor-move');
    }
    // The entry beat's admissible set is the two skills the author routed
    // out of `support` — from the move itself, not from a refusal.
    expect(beats[0]!.reachable!.ids).toEqual(['billing', 'account']);
  });

  it('carries the assembled system prompt, verbatim, because the producer opted in', () => {
    const withPrompt = route.hops.filter((h) => h.systemPromptText !== undefined);
    expect(withPrompt.length).toBeGreaterThan(0);
    expect(withPrompt[0]!.systemPromptText).toContain('You are a customer support agent.');
  });

  it('the topology says where the map came from: recording-declared, complete, with entries', () => {
    const topo = selectSkillTopology({ route });
    expect(topo.declaredSource).toBe('recording-declared');
    expect(topo.declaredComplete).toBe(true);
    expect(topo.entryIds).toEqual(['support']);
    expect(topo.nodes.find((n) => n.id === 'support')!.isEntry).toBe(true);
    expect(topo.nodes.find((n) => n.id === 'billing')!.isEntry).toBe(false);
    // The never-fired declared edge is drawable, declared, and not observed.
    const unfired = topo.edges.find((e) => e.id === 'disputes->security')!;
    expect(unfired.declared).toBe(true);
    expect(unfired.observed).toBe(false);
  });
});

describe('a pre-9.50.0 recording — the fallbacks, against the real old-shape artifact', () => {
  const route = routeFrom(OLD_ERA);

  it('the declared set stays the fired lower bound, and the fold says so', () => {
    expect(route.declaredComplete).toBe(false);
    expect(route.entryIds).toBeUndefined();
    // `routing[]` names an edge once it FIRES — this run fired exactly one.
    expect(route.declaredEdges.map((e) => `${e.from}->${e.to}`)).toEqual(['billing->refunds']);
    expect(selectSkillTopology({ route }).declaredSource).toBe('recording');
    expect(selectSkillTopology({ route }).declaredComplete).toBe(false);
    expect(selectSkillTopology({ route }).entryIds).toEqual([]);
  });

  it('no hop claims a fact its era never recorded', () => {
    for (const hop of route.hops) {
      expect(hop.reachable).toBeUndefined();
      expect(hop.systemPromptText).toBeUndefined();
    }
  });

  it('beats fall back to the refusal and declared-edge sources — tagged honestly', () => {
    const beats = selectSkillBeats({ route });
    const sources = beats.map((b) => b.reachable?.source);
    // The refused iteration carries the gate's own list; later beats at
    // `billing` see only the one fired edge; the rest honestly have nothing.
    expect(sources).not.toContain('cursor-move');
    expect(sources).toContain('refusal');
    expect(sources).toContain('declared-edges');
  });
});
